using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using blogProject.Models.Blog;

namespace App.Models.Blog
{
    [Table("Post")]
    public class Post
    {
        [Key]
        public int PostId { set; get; }

        [Required(ErrorMessage = "Please enter {0}")]
        [StringLength(160, MinimumLength = 5, ErrorMessage = "{0} last from {1} to {2} characters")]
        public string? Title { set; get; }

        [Display(Name = "Short Description")]
        public string? Description { set; get; }

        [Display(Name = "Url", Prompt = "Enter or auto generated by Title")]
        [StringLength(160, MinimumLength = 5, ErrorMessage = "{0} last from {1} to {2}")]
        [RegularExpression(@"^[a-z0-9-]*$", ErrorMessage = "Only accept [a-z0-9-] characters")]
        public string? Slug { set; get; }

        public string? Content { set; get; }
        public bool Published { set; get; }

        public List<PostCategory>? PostCategories { get; set; }

        // [Required]
        [Display(Name = "Author")]
        public string? AuthorId { set; get; }
        [ForeignKey("AuthorId")]
        [Display(Name = "Author")]
        public AppUser? Author { set; get; }

        [Display(Name = "Date Created")]
        public DateTime DateCreated { set; get; }

        [Display(Name = "Date Updated")]
        public DateTime DateUpdated { set; get; }

        [Display(Name = "Post Image")]
        public string? ImageFile { get; set; }

    }
}